# Generated by Django 3.2.7 on 2021-10-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_cast_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='Male', max_length=6),
        ),
    ]
