# Generated by Django 3.1.2 on 2021-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20211023_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='celebrities',
            field=models.ManyToManyField(blank=True, related_name='movie_celeb', to='movie.Cast'),
        ),
    ]
