# Generated by Django 3.1.2 on 2021-10-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20211025_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='Not Updated Yet', max_length=10000),
        ),
    ]
