# Generated by Django 3.2.7 on 2021-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20211027_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
